name: Unit Tests
run-name: Unit Testing ${{ github.ref_name }}

on:
  workflow_dispatch:
  push:
    paths: 
      - 'pds/'
      - '.github/workflows/tests.yml'

defaults:
  run:
    shell: bash

jobs:
  unittest:
    name: Running Unit tests
    runs-on: ubuntu-latest
    container:
      image: python:3.9
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create virtual env and activate
        run: |
          python -m venv env

      - name: Get requirements
        run: |
          source env/bin/activate
          python -m pip install -r requirements.txt
          

      - name: Run tests
        run: | 
          source env/bin/activate
          python -m unittest discover -s . -p *_test.py